### ISSUE TITLE
Failed to disconnect signal when editing config item with PySide2

### ISSUE THREAD

**Issue by titusjan** [titusjan/argos#13]
When using the PySide2 binding the following error occurs when you close a spin box editor in the Config Tree (i.e. when you have filled in a value and select a new config item to edit).

Traceback (most recent call last):
  File "/Users/kenter/prog/py/argos/argos/config/configtreeview.py", line 102, in closeEditor
    configItemDelegate.finalizeEditor(editor)
  File "/Users/kenter/prog/py/argos/argos/config/configitemdelegate.py", line 69, in finalizeEditor
    editor.finalize()
  File "/Users/kenter/prog/py/argos/argos/config/intcti.py", line 126, in finalize
    super(IntCtiEditor, self).finalize()
  File "/Users/kenter/prog/py/argos/argos/config/abstractcti.py", line 573, in finalize
    self.resetButton.clicked.disconnect(self.resetEditorValue)
RuntimeError: Failed to disconnect signal clicked().

When you close a combobox editor the following error occurs.

Traceback (most recent call last):
  File "/Users/kenter/prog/py/argos/argos/config/configtreeview.py", line 102, in closeEditor
    configItemDelegate.finalizeEditor(editor)
  File "/Users/kenter/prog/py/argos/argos/config/configitemdelegate.py", line 69, in finalizeEditor
    editor.finalize()
  File "/Users/kenter/prog/py/argos/argos/config/choicecti.py", line 226, in finalize
    self._comboboxListView.removeEventFilter(self)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QAbstractItemView) already deleted.

Might be related to #12

**Comment by titusjan** [comment]
By the way this is on OS-X 10.14.6

```
Python         : 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
pyside2        : 5.12.4 (Qt: 5.12.1)
numpy          : 1.17.0
scipy          : 1.3.1
pandas         : 0.25.0
pyqtgraph      : 0.11.0.dev0
exdir          : 
pgcolorbar     : 1.0.0
cmlib          : 1.0.1
h5py           : 2.9.0 (libhdf5: 1.10.5)
netCDF4        : 1.5.1.2 (libncdf4: 4.6.2, libhdf5: 1.10.5)
pillow (PIL)   : 6.1.0
argos          : 0.3.0.rc2 (debugging-mode)
```
