### ISSUE TITLE
TypeError when trying to open image plot

### ISSUE THREAD

**Issue by mfurseman** [titusjan/argos#25]
I've got a file which displays under the table view fine, however when opening the image plot I get an error:

```
2022-07-26 13:56:37.178 :               abstract.py:230  : ERROR   : Error while drawing the inspector: Text reading control character must be a single unicode character or None; but got: ', ' ----
2022-07-26 13:56:37.178 :               abstract.py:231  : ERROR   : Text reading control character must be a single unicode character or None; but got: ', '
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.9/site-packages/argos/inspector/abstract.py", line 201, in updateContents
    self._drawContents(reason=reason, initiator=initiator)
  File "/home/foo/.local/lib/python3.9/site-packages/argos/inspector/pgplugins/imageplot2d.py", line 557, in _drawContents
    self.config.updateTarget()
  File "/home/foo/.local/lib/python3.9/site-packages/argos/config/abstractcti.py", line 288, in updateTarget
    child.updateTarget(level = level + 1)
  File "/home/foo/.local/lib/python3.9/site-packages/argos/config/abstractcti.py", line 288, in updateTarget
    child.updateTarget(level = level + 1)
  File "/home/foo/.local/lib/python3.9/site-packages/argos/config/abstractcti.py", line 286, in updateTarget
    self._updateTargetFromNode()
  File "/home/foo/.local/lib/python3.9/site-packages/argos/inspector/pgplugins/pgctis.py", line 972, in _updateTargetFromNode
    lut = self.data.rgb_uint8_array
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/cmap.py", line 346, in rgb_uint8_array
    self.load_rgba_uint8_array()
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/cmap.py", line 366, in load_rgba_uint8_array
    rgb_ints = self._read_rgb_uint8_file(file_name)
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/cmap.py", line 328, in _read_rgb_uint8_file
    rgb_floats = load_rgb_floats(file_name)
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/misc.py", line 87, in load_rgb_floats
    array = np.loadtxt(source_file, delimiter=delimiter, dtype=dtype, **kwargs)
  File "/home/foo/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1308, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/foo/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
TypeError: Text reading control character must be a single unicode character or None; but got: ', '
2022-07-26 13:56:37.192 :                   misc.py:114  : CRITICAL: Bug: uncaught TypeError
```

**Comment by titusjan** [comment]
Which Argos and library versions do you have? Can you please copy/paste the versions from the about box?

Can you somehow give me access to this file?

Looking at the error, it seem to me that this error is related to reading the color maps. What happens if you select a different color map by clicking on the color map selection dialog. See red circle in screen shot.

<img width="1394" alt="Screenshot 2022-07-26 at 15 10 41" src="https://user-images.githubusercontent.com/3320415/181014419-6525a2d5-c428-45f2-93f6-b718c1a169e4.png">

**Comment by mfurseman** [comment]
With `QT_API=pyside2 python3.9 -m argos filename.nc` I'm able to keep the GUI open, although the Exception trace is still the same on all the color map fields.

**Comment by titusjan** [comment]
Yes `cmlib` is also mine.

So does this error occur only for that specific file? Or does it occur with any file?

**Comment by titusjan** [comment]
What happens if you run the `cmlib_demo` command? See [here](https://github.com/titusjan/cmlib#running-the-demo)

**Comment by mfurseman** [comment]
I get the same error, so that ties it down to something in cmlib. Are you happy to continue discussing here?

```
$ ~/.local/bin/cmlib_demo
Traceback (most recent call last):
  File "/home/foo/.local/bin/cmlib_demo", line 8, in <module>
    sys.exit(main())
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/demo.py", line 293, in main
    win = DemoWindow(cmLibModel=cmLibModel)
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/demo.py", line 226, in __init__
    self.updateSelectedLabel(self.selectionWidget.getCurrentColorMap())
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/demo.py", line 248, in updateSelectedLabel
    self.updateImageLabel(colorMap)
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/demo.py", line 255, in updateImageLabel
    pixMap = colorizeImageArray(self._imageArray, colorMap=colorMap,
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/demo.py", line 134, in colorizeImageArray
    rgba_arr = colorMap.rgba_uint8_array
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/cmap.py", line 357, in rgba_uint8_array
    self.load_rgba_uint8_array()
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/cmap.py", line 366, in load_rgba_uint8_array
    rgb_ints = self._read_rgb_uint8_file(file_name)
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/cmap.py", line 328, in _read_rgb_uint8_file
    rgb_floats = load_rgb_floats(file_name)
  File "/home/foo/.local/lib/python3.9/site-packages/cmlib/misc.py", line 87, in load_rgb_floats
    array = np.loadtxt(source_file, delimiter=delimiter, dtype=dtype, **kwargs)
  File "/home/foo/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1308, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/foo/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
TypeError: Text reading control character must be a single unicode character or None; but got: ', '
```

**Comment by titusjan** [comment]
Yes we can continue discussing here. I can try to reproduce it later this evening.

Do you use Linux or MacOS?

**Comment by titusjan** [comment]
Accidentally pressed the close button a bit too early, but I have fixed the issue. I could reproduce it when I upgraded Numpy to version 1.23.1. It was an easy fix.

I have made a new release of `cmlib`:  version 1.1.3. If you update to that version it should work. Please let me know if it doesn't.

**Comment by mfurseman** [comment]
Installed `cmlib-1.1.3` and we're back in business!

![image](https://user-images.githubusercontent.com/5279818/181192365-2575b6c9-534a-4769-8b34-936e43cd5725.png)

Thanks for the prompt assistance. Argos is my favourite NetCDF viewer, everything you need and nothing you don't.
